root: true
env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/recommended
  - plugin:@typescript-eslint/recommended
  - prettier # Make sure "prettier" is the last element in this list.
parser: vue-eslint-parser # Most eslint-plugin-vue rules require vue-eslint-parser to check <template> ASTs.
parserOptions:
  ecmaVersion: latest
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules:
  "vue/multi-word-component-names": "off"
